Controllers/RunController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CoExp_Web.Models;
using CoExp_Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using System.IO;

namespace CoExp_Web.Controllers
{
    /// <summary>
    /// Controller to return views.
    /// </summary>
    public class RunController : Controller
    {


        public IActionResult Index() { 
            return View();
        }

        public IActionResult Catalogue(CoexpParams coexpParams)
        {
            try
            {
                return View(coexpParams);
            }
            catch (Exception e)
            {
                ErrorViewModel errorModel = new ErrorViewModel()
                {
                    Message = e.Message
                };
                return View("Error", errorModel);
            }
        }

        public IActionResult Annotated(CoexpParams coexpParams)
        {
            try
            {
                return View(coexpParams);
            }
            catch (Exception e)
            {
                ErrorViewModel errorModel = new ErrorViewModel()
                {
                    Message = e.Message
                };
                return View("Error", errorModel);
            }
        }

        public IActionResult Help()
        {
            try
            {
                return View();
            }
            catch (Exception e)
            {
                ErrorViewModel errorModel = new ErrorViewModel()
                {
                    Message = e.Message
                };
                return View("Error", errorModel);
            }
        }
        public IActionResult About()
        {
            try
            {
                return View();
            }
            catch (Exception e)
            {
                ErrorViewModel errorModel = new ErrorViewModel()
                {
                    Message = e.Message
                };
                return View("Error", errorModel);
            }
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Plot()
        {
            try
            {
                return View();
            }
            catch (Exception e)
            {
                ErrorViewModel errorModel = new ErrorViewModel()
                {
                    Message = e.Message
                };
                return View("Error", errorModel);
            }
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Terms()
        {
            try
            {
                return View("TermsAndConditions");
            }
            catch (Exception e)
            {
                ErrorViewModel errorModel = new ErrorViewModel()
                {
                    Message = e.Message
                };
                return View("Error", errorModel);
            }
        }
        public IActionResult Datasets()
        {
            try
            {
                return View();
            }
            catch (Exception e)
            {
                ErrorViewModel errorModel = new ErrorViewModel()
                {
                    Message = e.Message
                };
                return View("Error", errorModel);
            }
            
        }
        public IActionResult Privacy()
        {
            try
            {
                return View();
            }
            catch (Exception e)
            {
                ErrorViewModel errorModel = new ErrorViewModel()
                {
                    Message = e.Message
                };
                return View("Error", errorModel);
            }
        }

        public IActionResult Help_Introduction()
        {
            try
            {
                return View();
            }
            catch (Exception e)
            {
                ErrorViewModel errorModel = new ErrorViewModel()
                {
                    Message = e.Message
                };
                return View("Error", errorModel);
            }
        }
        public IActionResult Help_Catalogue()
        {
            try
            {
                return View();
            }
            catch (Exception e)
            {
                ErrorViewModel errorModel = new ErrorViewModel()
                {
                    Message = e.Message
                };
                return View("Error", errorModel);
            }
        }
        public IActionResult Help_Annotation()
        {
            try
            {
                return View();
            }
            catch (Exception e)
            {
                ErrorViewModel errorModel = new ErrorViewModel()
                {
                    Message = e.Message
                };
                return View("Error", errorModel);
            }
        }
        public IActionResult Help_Plot()
        {
            try
            {
                return View();
            }
            catch (Exception e)
            {
                ErrorViewModel errorModel = new ErrorViewModel()
                {
                    Message = e.Message
                };
                return View("Error", errorModel);
            }
        }

        public IActionResult Publication()
        {
            try
            {
                return View();
            }
            catch (Exception e)
            {
                
                this.LogError(e);
                ErrorViewModel errorModel = new ErrorViewModel()
                {
                    Message = e.Message
                };
                return View("Error", errorModel);
            }
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private void LogError(Exception ex)
        {
            string message = string.Format("Time: {0}", DateTime.Now.ToString("dd/MM/yyyy hh:mm:ss tt"));
            message += Environment.NewLine;
            message += "-----------------------------------------------------------";
            message += Environment.NewLine;
            message += string.Format("Message: {0}", ex.Message);
            message += Environment.NewLine;
            message += string.Format("StackTrace: {0}", ex.StackTrace);
            message += Environment.NewLine;
            message += string.Format("Source: {0}", ex.Source);
            message += Environment.NewLine;
            message += string.Format("TargetSite: {0}", ex.TargetSite.ToString());
            message += Environment.NewLine;
            message += "-----------------------------------------------------------";
            message += Environment.NewLine;
            string path = @"~/MyTest.txt";

            //// This text is added only once to the file.

            //File.WriteAllText(path, message);
            

            //// This text is always added, making the file longer over time
            //// if it is not deleted.
            //string appendText = "This is extra text" + Environment.NewLine;
            //File.AppendAllText(path, appendText);

            //// Open the file to read from.
            //string readText = File.ReadAllText(path);
            //Console.WriteLine(readText);
            //string path = Server.MapPath("~/ErrorLog.txt");
            using (StreamWriter writer = new StreamWriter(path, true))
            {
                writer.WriteLine(message);
                writer.Close();
            }
        }
    }
}

Views/Run/Catalogue.cshtml
@model CoexpParams
@{
    //View of the main page
    ViewData["Title"] = "Network Catalogue";
}

@Html.HiddenFor(m => m.Category)
@Html.HiddenFor(m => m.Network)
@Html.HiddenFor(m => m.ModuleColor)
@Html.HiddenFor(m => m.Genes)


<div class="breadcrumb">
    @if (ViewContext.RouteData.Values["controller"].ToString() != "Home")
    {
        <span class="main-label-breadcrumbs">CoExp</span>@*@Html.ActionLink(ViewContext.RouteData.Values["controller"].ToString(), "Index", ViewContext.RouteData.Values["controller"].ToString())*@
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="active">Network Catalogue</span>
    }
</div>
<div class="row">
    <div id="menu" class="col-sm-3 col-md-3 col-lg-3 sidebar menu">
        <div id="menu_gene_list" class="hidden">
            <h4>Gene List</h4>
            <hr class="menu-hr" />
            <h5>Please, click the button below to download the gene list of this module:</h5>
            <button id="get_gene_list" type="button" class="btn btn-info">Get Gene List</button>
        </div>

        <div id="menu_data">

            <div id="step1">
                <span class="fa-li" data-toggle="tooltip"
                      data-placement="right"
                      data-html="true"
                      title="<p><b>Category</b> of gene co-expression networks. For further information, please visit the <a href='@Url.Action("Datasets", "Run")' target='_blank'>Datasets</a> section.</p>">
                    <i class="fa fa-info-circle fa-fw"></i>
                </span><p class="fa-li-p" for="category_dropdown">Category:</p>
                
                <select id="category_dropdown" name="category" class="selectpicker" title="Select an option ...">
                </select>
            </div><br>

            <div id="step2">
                <span class="fa-li" data-toggle="tooltip"
                      data-placement="right"
                      data-html="true"
                      title="<p><b>Gene co-expression networks</b> that belong to the selected category. For further information, please visit the <a href='@Url.Action("Datasets", "Run")' target='_blank'>Datasets</a> section.</p>">
                    <i class="fa fa-info-circle fa-fw"></i>
                </span><p class="fa-li-p" for="network_dropdown">Network:</p>
                
                <select id="network_dropdown" name="network" class="selectpicker" title="Select an option ...">
                    <option></option>
                </select>
            </div> <br>

            <div id="step3">
                <span class="fa-li" data-toggle="tooltip"
                      data-placement="right"
                      data-html="true"
                      title="These are the different types of results that can be retrieved in this query. You can select only one or both views.">
                    <i class="fa fa-info-circle fa-fw"></i>
                </span><p class="fa-li-p" for="view_selection">Show results by ...</p>
                
                <select id="view_selection" class="selectpicker" multiple title="Select an option ...">
                    <option value="1">Gene Ontology</option>
                    <option value="2">Cell Type</option>
                </select>
            </div>

            <hr class="menu-hr" />

            <div id="step4">
                <button id="send_button" class="btn btn-primary">Accept</button>
            </div>
        </div>
    </div>

    <div id="step5" class="col-md-9">

        <div id="empty-initial-results">
            <p>Your results will appear here.</p>
        </div>

        <!-- Nav tabs -->
        <ul id="tabs" class="nav nav-tabs" style="display:none">
            <li class="active"><a href="#tab1" data-toggle="tab">Ontology view</a></li>
            <li><a href="#tab2" data-toggle="tab">Cell Type view</a></li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div class="tab-pane fade in active" id="tab1">
                <div id="goFromTissue_div" style="display:none">
                    <h2>Ontology view</h2>
                    <p>
                        The datatable below displays data in rows and columns, with one row for each module belonging to the co-expression network selected. The columns provide information related to the
                        ontology term that more strongly correlates with the genes clustered within each module.
                        The p-value column supports the overlap between the ontology term returned and the genes clustered within the current module.
                        The raw data behind the generation of this data table is available to be downloaded on the three buttons placed on the upper-left-side corner of the table.
                    </p>
                    <br>
                    <table id="goFromTissue_table" class="table table-striped table-bordered wrap"></table>
                </div>


            </div>
            <div class="tab-pane fade" id="tab2">
                <div id="cellType_div" style="display:none;">
                    <h2>Cell Type view</h2>
                    <p>
                        The datatable below displays in the columns all modules that belong to the co-expression network selected. The rows contain information associated to the different cell types.
                        The intersection between each row and column contains a p-value, corrected by the Bonferroni method, that supports the linkage between each cell type and all genes found in the corresponding module.
                        The raw data supporting the generation of this data table is available to be downloaded under the three buttons placed on the upper-left-side corner of the table.
                    </p>
                    <br>
                    <table id="cellType_table" class="table table-striped table-bordered nowrap table-responsive"></table>
                </div>
            </div>
        </div>
        <div id="error" style="display:none;" class="alert alert-danger">
            <h4>Sorry, a temporary error has occurred during the data retrieval.</h4>
            <h5>The webmaster has already been informed about this error and it will be sorted shortly. <br />Please, try again later.</h5>
        </div>

    </div>
    <div class="loading_layer"><!-- loading layer --></div>

</div>
@section HeadStyles{
    
}
@section Scripts{

    <script type="text/javascript">
        // Turn active current menu's option
        $(".nav-item").find(".active").removeClass("active");
        $("#tab_network_catalogue").addClass("active");
    </script>

   
    <script type="text/javascript">

        $(document).ready(function () {

            // Initiate the tooltips

            $('[data-toggle="tooltip"]').tooltip()

            $("[data-placement='bottom']").popover();

            $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
                $($.fn.dataTable.tables(true)).DataTable()
                    .columns.adjust();
            });

            const modelReceived = @(Model.ModuleColor == null ? 0 : 1);

            //If the model doesn't have any data:
            if (modelReceived == 0)
                API.prototype.menuInit(1);
            else {
                API.prototype.menuInit(11);
            }

        });

        // Code for the initial tour (i.e. the aid)
          function startIntro(){
            var intro = introJs();
              intro.setOptions({
                  disableInteraction: true,
                  steps: [
                      {
                          element: '#step1',
                          intro: "<p><b>Category</b></p><p>Please, select here a category of co-expression networks.<br/><br/>It has been pre-selected the <b>'10UKBEC'</b> category. For further information about the networks, please visit the <a href='@Url.Action("Datasets", "Run")' target='_blank'>Datasets</a> section.</p>",
                          position: 'right',
                          scrollTo: 'tooltip'
                      },
                      {
                          element: '#step2',
                          intro: "<b>Network</b><br/><br/>These are all gene co-expression networks that belong to the category selected in the previous step.<br/><br/>It has been pre-selected the <b>'SNIG'</b> network. For further information about the networks, please visit the <a href='@Url.Action("Datasets", "Run")' target='_blank'>Datasets</a> section.</p>",
                          position: 'right'
                      },
                      {
                          element: '#step3',
                          intro: "<b>Show results by...</b><br/><br/>These are the different types of results that can be retrieved in this query.<br/><br/>Only the <b>'Gene Ontology'</b> view has been pre-selected by default. You can select only one or both views.",
                          position: 'right'
                      },
                      {
                          element: '#step4',
                          intro: "<b>Accept</b><br/><br/>Once you are ready, press this button to submit your query.",
                          position: 'right'
                      },
                      {
                          element: '#step5',
                          intro: "<b>Results</b><br/><br/>This is the results area.",
                          position: 'bottom'
                      }
                  ]
              });
              intro.onbeforechange(function (targetElement) {

                  if (targetElement.id == "step1") {
                      $('#category_dropdown').val('10UKBEC').change();
                      $('#category_dropdown')
                          .prop("disabled", false)
                          .selectpicker('refresh');
                  }
                  if (targetElement.id == "step2" && $("#category_dropdown").val() == "10UKBEC") {
                      $('#network_dropdown').val('SNIG').change();
                      $('#network_dropdown')
                          .prop("disabled", false)
                          .selectpicker('refresh');
                  }
                  if (targetElement.id == "step3") {
                      $('#view_selection').val('1').change();
                      $('#view_selection')
                          .selectpicker('refresh');
                  }
              });

              var doneTourCatalogue = sessionStorage.getItem('EventTourCatalogue') === 'Completed';
              if (doneTourCatalogue) {
                  $('#category_dropdown').val('10UKBEC').change();
                  $('#category_dropdown')
                      .prop("disabled", false)
                      .selectpicker('refresh');
                  return;
              }
              else {
                  if (environment != "ATN_5843218Gt") {
                      intro.start();

                      intro.oncomplete(function () {
                          sessionStorage.setItem('EventTourCatalogue', 'Completed');
                      });

                      intro.onexit(function () {
                          sessionStorage.setItem('EventTourCatalogue', 'Completed');
                      });
                  }
              }
          }

    </script>
}

Views/Run/Help.cshtml
@{
    ViewData["Title"] = "Help";
}
<div class="breadcrumb">
    @if (ViewContext.RouteData.Values["controller"].ToString() != "Home")
    {
        <span class="main-label-breadcrumbs">CoExp</span>
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="active">Help</span>
        @*@Html.ActionLink(ViewContext.RouteData.Values["controller"].ToString(), "Index", ViewContext.RouteData.Values["controller"].ToString())*@
    }
    @*@if (ViewContext.RouteData.Values["action"].ToString() != "Index")
        {
            @Html.ActionLink(ViewContext.RouteData.Values["action"].ToString(), ViewContext.RouteData.Values["action"].ToString(), ViewContext.RouteData.Values["controller"].ToString())
        }*@
</div>
<div class="row">
    <div class="col-11 about">
        <h2>Getting started with CoExp Web Application</h2>
        <small>Updated: Jan 04, 2021</small>
        <p class="author">
            by <a href="https://rytenlab.com/RytenLab/MemberInfo?Id=BP98-F74160" target="_blank" title="Juan A. Botía">Juan A. Botía</a> and
            <a href="https://rytenlab.com/RytenLab/MemberInfo?Id=LO96_F34158" target="_blank" title="Sonia García-Ruiz">Sonia García-Ruiz</a>
        </p>
        <hr class="menu-hr" />
        <div>
            <p>
                CoExp Web Application is a web-based tool developed using the ASP.NET Core Framework and built with the aim of facilitating the use of the family of <a href="https://github.com/juanbot/CoExpNets" target="_blank" title="CoExpNets R package available on GitHub">CoExpNets</a> R packages (author: Juan A. Botía) outside a command-line environment.
                We have built CoExp Web Application through a web-page formatting because we believe a web-page structure will make CoExpNets networks easily accessible to every potential user around the world, at any time and from any device they decide to do so, without the inconvenience and difficulty of configurating a command-line environment.
                In this sense, all networks and models made available through the family of CoExpNets R packages are ready to be used on CoExp Web Application. In addition, they are also free to <b>be used for your own research</b>.
                <br /><br />
                The tutorial below explains how to effectively use CoExp Web Application in four main sections:
            </p>

            <br /><h4><a asp-area="" asp-controller="Run" asp-action="Help_Introduction">INTRODUCTION</a></h4><br />
            <p>
                This is the "Getting Started" tutorial. It contains the details of the case-of-use we have defined for this tutorial.
            </p>

            <br /><h4><a asp-area="" asp-controller="Run" asp-action="Help_Catalogue">NETWORK CATALOGUE</a></h4><br />
            <p>
                This is the second tutorial of the series. It contains information about how to use the 'Network Catalogue' tab.
            </p>

            <br /><h4><a asp-area="" asp-controller="Run" asp-action="Help_Annotation">GENE SET ANNOTATION</a></h4><br />
            <p>
                This is the third tutorial of the series. It contains information about how to use the 'Gene Set Annotation' tab.
            </p>

            <br /><h4><a asp-area="" asp-controller="Run" asp-action="Help_Plot">PLOT GENE NETWORK</a></h4><br />
            <p>
                This is the fourth tutorial of the series. It contains information about how to use the 'Plot Gene Network' tab.
            </p>
        </div>
    </div>
</div>

@section Scripts{

    <script type="text/javascript">
    $(document).ready(function () {
        // Turn active current menu's option
        $(".nav-item").find(".active").removeClass("active");
        $("#tab_help").addClass("active");
    });

    </script>
}

Views/Run/Help_Introduction.cshtml
@{
        ViewData["Title"] = "Help_Introduction";
}

    <div class="breadcrumb">
        @if (ViewContext.RouteData.Values["controller"].ToString() != "Home")
        {
            <span class="main-label-breadcrumbs">CoExp</span>
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="active">Help - Introduction</span>
        }
    </div>
    <div class="row">
        <div class="col-11 about">
            <h2>Introduction</h2>
            <small>Created: April 04, 2019<br />Last updated: November 20, 2019</small>
            <p class="author">
                by <a href="https://rytenlab.com/RytenLab/MemberInfo?Id=BP98-F74160" target="_blank" title="Juan A. Botía">Juan A. Botía</a> and
                <a href="https://rytenlab.com/RytenLab/MemberInfo?Id=LO96_F34158" target="_blank" title="Sonia García-Ruiz">Sonia García-Ruiz</a>
            </p>
            <hr />
            <p>This is the first part of the tutorial series <a asp-area="" asp-controller="Run" asp-action="Help">"Getting started with CoExp Web Application"</a>.</p>
            <div>
                <h3><a id="introduction" style="color:black;">Introduction</a></h3>

                <p>Let us suppose that we have a list of genes that we would like to annotate in the CoExp Web Application. In this example, we would be interested in answering the following questions:</p><br />
                <ul>
                    <li>Does our set of genes cluster together within a specific co-expression module in a particular tissue? If so, is that clustering happening more
                        significantly than would be expected by simple chance?
                    </li>
                    <li>Is the module in which the group of genes clusters together enriched by genes with a specific biological function?
                    If so, what is the reliability of that prediction for each gene of interest?
                    </li>
                    <li>
                        Is the module in which the group of genes clusters together enriched for any kind of cell-type-specific marker?
                    </li>
                    <li>
                        Is the clustering of the genes-of-interest unique to a specific module and tissue?
                        Or, on the contrary, has it been observed within multiple gene co-expression networks?

                    </li>
                </ul><br />
                <p>Let us also suppose that our initial list of genes is composed of the monogenic forms of Parkinson's disease (PD), obtained from the Genomics England panel App (only the green genes):</p><br />
                <blockquote>
                    <p>ATP13A2 ATP1A3 C19orf12 CSF1R DCTN1 DNAJC6 FBXO7 FTL GBA GCH1 GRN LRRK2 LYST MAPT OPA3 PANK2 PARK7 PINK1 PLA2G6 PRKN PRKRA RAB39B SLC30A10 SLC39A14 SLC6A3 SNCA SPG11 SPR SYNJ1 TH TUBB4A VPS13A VPS35 WDR45</p>
                </blockquote><br />
                             <p>
                                 Thus, in order to answer the list of questions detailed above, the first thing we have to do is to choose which are the conditions in which we would like to study the genes.
                                 For that purpose, we will firstly surf through the network catalogue of genes available within the tab 'Network Catalogue' on the CoExp Web Application tool.
                             </p>
                <br />

                <p><span class="glyphicon glyphicon-chevron-right"></span><b>Next: </b><a asp-area="" asp-controller="Run" asp-action="Help_Catalogue">Surfing the Network Catalogue</a></p>
            </div>
        </div>
    </div>

    @section Scripts{

        <script type="text/javascript">
        $(document).ready(function () {
            // Turn active current menu's option
            $(".nav-item").find(".active").removeClass("active");
            $("#tab_help").addClass("active");
        });
        </script>
    }

Views/Run/Help_Plot.cshtml
@{ ViewData["Title"] = "Help_Plot"; }

<div class="breadcrumb">
    @if (ViewContext.RouteData.Values["controller"].ToString() != "Home")
    {
<span class="main-label-breadcrumbs">CoExp</span>
                <span class="glyphicon glyphicon-chevron-right"></span>
                                <span class="active">Help - Plot Gene Network</span>}
</div>
<div class="row">
    <div class="col-11 about">
        <h2>Plot Gene Network</h2>
        <div>
            <br />
            <h3>Plot Gene Network</h3>
            <span>
                <b>'Plot Gene Network'</b> has been created to represent the most important genes neighbouring a gene/genes of interest through an undirected graph.
            </span>

            <div class="center-block text-center">
                <video width="420" height="340" controls class="text-center">
                    <source src="~/images/help/CoExp_plot.mp4" type="video/mp4">
                </video>
            </div>
            <br /><br />

            <p>
                Following up with the example shown in <a asp-area="" asp-controller="Run" asp-action="Help_Annotation">'Gene Set Annotation'</a> tutorial, let us now visualize the gene 'ATP1A3' from the 'yellow' module,
                'SNIG' network and '10UKBEC' category and its most important neighbouring genes.<br />After clicking the 'Accept' button, the plot is generated and the gene 'ATP1A3' appears as a <b>very important gene within its module as it presents a node with a very high size</b>.
                In addition, a total number of 16 other genes appear neighbouring it.
            </p><br />
            <div class="figure">
                <img src="~/images/help/plot.PNG"
                     alt="Available categories" title="Fig1: Available categories." />
            </div><br /><br />
            <p><span class="glyphicon glyphicon-chevron-left"></span><b>Previous tutorial: </b><a asp-area="" asp-controller="Run" asp-action="Help_Annotation">Gene Set Annotation</a></p><br />
        </div>
    </div>
</div>

@section Scripts{

    <script type="text/javascript">$(document).ready(function () {
            // Turn active current menu's option
            $(".nav-item").find(".active").removeClass("active");
            $("#tab_help").addClass("active");
        });</script>
}

Views/Run/Index.cshtml
@{
    ViewData["Title"] = "CoExp Web Application";
}


<div class="row">

    <div class="col-sm-6 col-lg-6 col-md-6">
        <div class="home-video">
            <video autoplay="" loop="" muted="" class="vid-bg aos-init aos-animate" data-aos="fade-right" data-aos-delay="500">
                <environment include="Development">
                    <source type="video/mp4" src="/coexp_test/images/abstract_line1.mp4">
                </environment>
                <environment include="Production">
                    <source type="video/mp4" src="/coexp/images/abstract_line1.mp4">
                </environment>
                <environment include="Private">
                    <source type="video/mp4" src="/ATN_5843218Gt/images/abstract_line1.mp4">
                </environment>
                <environment include="Docker">
                    <source type="video/mp4" src="/Docker/images/abstract_line1.mp4">
                </environment>
            </video>
        </div>
    </div>
    <div class="col-sm-6 col-lg-6 col-md-6">
        <div class="home-text">
            <h1>CoExp Web Application</h1>
            <h2>Exploring networks by gene ontology and cell type</h2>
            <h2>Annotate a list with your preferred genes</h2>
            <h2>Plot your genes of interest</h2>
        </div>
    </div>

</div>